import type { Config } from "tailwindcss";

// Helper — wraps each token so Tailwind can apply opacity modifiers (bg-primary/50 etc.)
const c = (name: string) => `rgb(var(--${name}) / <alpha-value>)`;

const config: Config = {
  content: ["./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background:                   c("background"),
        surface:                      c("surface"),
        "surface-dim":                c("surface-dim"),
        "surface-bright":             c("surface-bright"),
        "surface-container-lowest":   c("surface-container-lowest"),
        "surface-container-low":      c("surface-container-low"),
        "surface-container":          c("surface-container"),
        "surface-container-high":     c("surface-container-high"),
        "surface-container-highest":  c("surface-container-highest"),
        "surface-variant":            c("surface-variant"),
        "on-surface":                 c("on-surface"),
        "on-surface-variant":         c("on-surface-variant"),
        "on-background":              c("on-background"),
        "inverse-surface":            c("inverse-surface"),
        "inverse-on-surface":         c("inverse-on-surface"),
        outline:                      c("outline"),
        "outline-variant":            c("outline-variant"),
        "surface-tint":               c("surface-tint"),
        primary:                      c("primary"),
        "on-primary":                 c("on-primary"),
        "primary-container":          c("primary-container"),
        "on-primary-container":       c("on-primary-container"),
        "inverse-primary":            c("inverse-primary"),
        secondary:                    c("secondary"),
        "on-secondary":               c("on-secondary"),
        "secondary-container":        c("secondary-container"),
        "on-secondary-container":     c("on-secondary-container"),
        tertiary:                     c("tertiary"),
        "on-tertiary":                c("on-tertiary"),
        "tertiary-container":         c("tertiary-container"),
        "on-tertiary-container":      c("on-tertiary-container"),
        error:                        c("error"),
        "on-error":                   c("on-error"),
        "error-container":            c("error-container"),
        "on-error-container":         c("on-error-container"),
        "primary-fixed":              c("primary-fixed"),
        "primary-fixed-dim":          c("primary-fixed-dim"),
        "on-primary-fixed":           c("on-primary-fixed"),
        "on-primary-fixed-variant":   c("on-primary-fixed-variant"),
        "secondary-fixed":            c("secondary-fixed"),
        "secondary-fixed-dim":        c("secondary-fixed-dim"),
        "on-secondary-fixed":         c("on-secondary-fixed"),
        "on-secondary-fixed-variant": c("on-secondary-fixed-variant"),
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        display: ["Manrope", "sans-serif"],
        h1: ["Manrope", "sans-serif"],
        h2: ["Manrope", "sans-serif"],
        h3: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        numeric: ["Inter", "sans-serif"],
      },
      fontSize: {
        display: ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        h1: ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        h2: ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        h3: ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        numeric: ["16px", { lineHeight: "1", fontWeight: "500" }],
      },
      boxShadow: {
        // Theme-aware layered elevation (values defined in globals.css :root / .dark)
        xs: "var(--shadow-xs)",
        card: "var(--shadow-card)",
        "card-hover": "var(--shadow-card-hover)",
        elevated: "var(--shadow-elevated)",
      },
      maxWidth: {
        container: "1280px",
      },
    },
  },
  plugins: [],
};

export default config;
